#ifndef _TEST_STATUSCODE_H
#define _TEST_STATUSCODE_H

void led_setting_is_valid_returns_TRUE_if_setting_is_OFF(void);
void led_setting_is_valid_returns_TRUE_if_setting_is_GREEN(void);
void led_setting_is_valid_returns_TRUE_if_setting_is_RED(void);
void led_setting_is_valid_returns_FALSE_if_setting_is_any_other_value(void);

#endif // _TEST_STATUSCODE_H
